
export const data = [
    {
      id: 1,
      name: "Camiseta Deportiva",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTQOvYvPd_tMO0gaS3cZfw6ny3rVGUoX0gM-1GplLpZR9K6iOG1QSEV093ZWQN0ClMkD85A4TQRsyZF5Hguw63IFmJZ1nZjVdoK6TuA0Xna&usqp=CAE",
      precio: 40000,
      stock: 10,
    },
    {
      id: 2,
      name: "Zapatillas para Correr",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQAeoh1eGhOV7_T713AF-oha7xjAfHD42lxwjsuz75-O1A-7sVR_xiLVb-PKAaDizt8Xz9p3c7wDpf7yr9RSx3RMsi9fSa6MaJS6RHyofAnqtXXBKr4Qq5DVjo&usqp=CAE",
      precio: 80000,
      stock: 15,
    },
    {
      id: 3,
      name: "Pesas de 2 kg",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT9OWeBTZNsO3viT7Fry9lRg_Lj59MKSuLtn_eoO3lXdX8IeeVPvh4z_cHcN7rs4w-Brqot1P_VZiW5LM-BxEMc3kOcXys6nWaL5qQjDAoUyQ9RYbOreQGOJA&usqp=CAE",
      precio: 30000,
      stock: 20,
    },
    {
      id: 4,
      name: "Pantalones Deportivos",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSHMGJA5OC9ecwnat-rrgdDYwwoZkEulW4vE7FdGVBLjItk2rupROv9GOL1quj6rIZd8vUNFG0--Qk08UKJZH06LrlfCcKXbbvi6vywEFc&usqp=CAE",
      precio: 60000,
      stock: 12,
    },
    {
      id: 5,
      name: "Bicicleta Estacionaria",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQZhk-Tw8DCBZ-dy555EroldQSWgPXPBJIaankN6EW5nqVh36Gmr_FeVqUZRQQzIozLRX_gkHILMvU1KboAaYry4fISozXupgyIUoOs4vy8w0NoavfkTc3grQ&usqp=CAE",
      precio: 120000,
      stock: 8,
    },
    {
      id: 6,
      name: "Gorra de Entrenamiento",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRb_AAdjJ_N2DY-RrOJrP172B9WHsiHlywcxdQtTND2e3hlkX0gYVrTO4b5ZGvKaJFzIrotTbCcNuUvPkesxZ9kYlVkNIoIwlc3Tcj9feJfLKg1mJKizSuZYqw&usqp=CAE",
      precio: 25000,
      stock: 25,
    },
    {
      id: 7,
      name: "Guantes para Levantamiento de Pesas",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS6dLWcdnUryzsoi6Wk8Bnyusid3wcEmZ4TXtOD1LxNbdhTbhf_KAquCXUbB-1t2wOgqms9fHCMTQOWgyQDIO6JF3aHfB1P_AamxEEf-sENqVzoItY66eh3wA&usqp=CAE",
      precio: 35000,
      stock: 18,
    },
    {
      id: 8,
      name: "Cuerda para Saltar",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRLDc_UYBdlmHbWIvGDvaZx8n7jAw1Ob8H4bqj6HdxiyveSH7_ZkPVNyCnt74JHsMoHRuDFpgW4cRc9UULlk_SpLqFjQTfhUpQAjt5vjmtiLDQwcyOX4R3_&usqp=CAE",
      precio: 15000,
      stock: 30,
    },
    {
      id: 9,
      name: "Bandas de Resistencia",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR_nq4rCLNlP_a9JOh2IbfMfUViwmrSUTsyIdl6goD2H1LLErAy5L-3n-cXVZgGTevkhUJeAafp7C5OnfgxfWvDTTD33o90fg&usqp=CAE",
      precio: 18000,
      stock: 22,
    },
    {
      id: 10,
      name: "Máquina de Abdominales",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSJiL8P6Cr-XkIQ6zoWc2skTjIKklzOldXFwFJaTM56IGysYujq6Ag0IQSkP1jJa_y1axIsnj3lVG7Wn0meOLLUSp4sH772DHcZwa8BHiYOQECN59-yrFyybA&usqp=CAE",
      precio: 90000,
      stock: 10,
    },
    {
      id: 11,
      name: "Pelota de Ejercicio",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRlEqtTIB43xaTbzaR3TeAp_IlOC28xIJWi4ppqMIG8anoZDR7MntOmFrPaY3LQmR3zid89HjatFZgqt1kUtkZLQp0KH-4mbfa5rUQ5JzKgO_2ItWf3eWJv&usqp=CAE",
      precio: 25000,
      stock: 15,
    },
    {
      id: 12,
      name: "Calcetines Deportivos",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSRL72c_O-P45iDiPIodIzuAKuigPPANtE-vZ8SV5KsGt7Q64vvQ49yEVs4alD9al5Lug_nrsDdTkQd4GdI29f-vGX6bXcgq5Vhis3fZ7UovQ7wRSQYz_TN4A&usqp=CAE",
      precio: 8000,
      stock: 40,
    },
    {
      id: 13,
      name: "Bloques de Yoga",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTlieGGZ10-UgWqYkpfE4UMKm0D1CDh1XBbNACCGijV4uYTvFUcd86GXhdNxIh8uWIst9qYRpPqSSfWKu13IYrcsFjeQxzHnU2qKqRjrM0vhQD4-GdooxQ7qA&usqp=CAE",
      precio: 12000,
      stock: 25,
    },
    {
      id: 14,
      name: "Mancuernas de 5 kg",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsMJPmnT0XNnhRipzdbS3bnIr_c9qlvV4MMz8nEg_3nHdDvWH5Wo6S1NdgT8TVor49N53isnBgC9Whsq3c0H1OMr-AIaa2m2EKam6x5LDEO75dR-ZLdh3msQ&usqp=CAE",
      precio: 40000,
      stock: 10,
    },
    {
      id: 15,
      name: "Reloj Deportivo",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTQEqqIZRrVKgA-iNZaH_GK3eAkAaRr2ZECyhu3401_hIMrP3pVgevOOz2Uf1jtR7kPsxJhxDkZdIiuNnanAWs-fsCtXwQMf9VNQILMUkqenQ8X13DHP6aNnsg&usqp=CAE",
      precio: 60000,
      stock: 12,
    },
    {
      id: 16,
      name: "Botella de Agua Deportiva",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRkhVs125EVnWZ6Z0ImppdgyEoejiCaMj4ip81gQIfD8jbN642fw-5OTl8Aa9HvXf5CnZECeuPDGGWVcPN1h1ly5hkxGS0gVTYiohOrqTn1hWuHwB1iVsffk58&usqp=CAE",
      precio: 5000,
      stock: 50,
    },
    {
      id: 17,
      name: "Cinta de Correr",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSZnX7itIZkbvRWOMtLDntTlkLP26twfZAbbnHTaqerQK3S9w8zxLQHm_lhzjoBeWaIzuaeDY1P91agOwTmX6VgKuZwT5NVbWnk0wiyZXkdOLxgpbd7nWnFqw&usqp=CAE",
      precio: 150000,
      stock: 5,
    },
    {
      id: 18,
      name: "Balón Medicinal",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTu5z7-wHuofMHd9wnofYaqvWCJragPWOCDDZGLSTiHjXC3zb_eEEh7UpQVQV3nbLq_kgTVQieqjTMoMKa4OFMo_UnmY31G1oio0v8y9WNKnVZ7RHStxSPN&usqp=CAE",
      precio: 30000,
      stock: 20,
    },
    {
      id: 19,
      name: "Mochila Deportiva",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT4lpR24aZxsoJ-o1kzZvNQy3aeNLfkcz4g9hB8RvK_hSE3AGy0CNLhpRYzdB_E1YX7yf8zqWKN6JnWbjVsEtXDp6Q1Z5ZpN227Zz7Amw6eD6aZNmQU9v9LveI&usqp=CAE",
      precio: 45000,
      stock: 15,
    },
    {
      id: 20,
      name: "Chaleco Reflectante para Correr",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTY4hynaC7KtXnR8XuFxX9-gTmm7rqFqb7AXUb-ZKjJBZ2OUovOvKJcysY-sUQF96fhH0mVSk47S_xK9NrfLGeWUbwJXUQaOppG6TVao_k6c4KujeyycQgCog&usqp=CAE",
      precio: 18000,
      stock: 22,
    },
    {
      id: 21,
      name: "Banda para Brazos",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSCYsW3FEQZbsGZs44qrqjGMIBhhiQCwUlSzyWfLBbXloCA9I7yri7Yu1_M0OyF01qvtM0jxM8e68CaqoFRyX9dmWxBTMepkm9yYayqa3E&usqp=CAE",
      precio: 10000,
      stock: 30,
    },
    {
      id: 22,
      name: "Step Aeróbico",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRtmpElSWF5CsP9sqX-2jhe1AoeYH16MT-B9c0LLis-8a9bJxcZjpoxJCokzA5d-SwyhVEHdIeqBw3X-2-IOa7LR7fQ0wUgX4PWakhENMPrPMnGPOnalGREXQ&usqp=CAE",
      precio: 35000,
      stock: 18,
    },
    {
      id: 23,
      name: "Calcetines de Compresión",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSJFSvI-EsJbOiDfpnDaq3PAmwDezR6zCR8W9ZfWbica8HQpidtk16B3t-omDZWA39z-2XWN9IAp9CuJStmbO-01ytNTjxn-PnpEQHq7oTu5NVApUCWN6fK2S4&usqp=CAE",
      precio: 12000,
      stock: 25,
    },
    {
      id: 24,
      name: "Banca de Pesas",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR6D_CAly6F5-uRrFGbgZKUkK95t4quMiK7ije87TFn3fgcQoYcwqtaPQChZc7Zok7-zSTqSOfE_umsqfNfLQKGfmbZeDPyY1jhgBOb7PE60nls0epthaF8Bw&usqp=CAE",
      precio: 70000,
      stock: 12,
    },
    {
      id: 25,
      name: "Termo para Bebidas Deportivas",
      imagen: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTXoM0m-8uPmd8fwHgK0Dj34eLtSCEzNzho33AFeX6UEIKCLi8-mjjKZhrTkQE5BitG23eP1KxajVMdMSzKr57yKGJNijZ2ORmufC79YvUTMANJYmfWpkmq65c&usqp=CAE",
      precio: 12000,
      stock: 30,
    },
    {
      id: 26,
      name: "Calcetines Térmicos para Running",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSFUVm7uDfJNuJo91HS1cG3bFMz-3TAjuJNVqLRG2b-k3KI-aYOtGlx9w3SMIL749QwN-mEQEiUNjLJaZCeMkcI3nQUxCP72o-hXe50ZgcJ-RX6MLzJ8Fkl&usqp=CAE",
      precio: 15000,
      stock: 28,
    },
    {
      id: 27,
      name: "Bolsa de Gimnasio",
      imagen: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR1eKgxdGh1P5wi9FypAFou5cxiKeR_ROerymZ4IzWbYDdb9GuJezjhbUcm0OeRyzA9_6I5ZahElNIQwGlgTl6jRJO0Ut9HrgjuwjnZocmRt1euYHt3NLCMQA&usqp=CAE",
      precio: 25000,
      stock: 20,
    },
    {
      id: 28,
      name: "Báscula Digital para Pesarse",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRe4gG2Suf1hJNKaxnWvwaTVP0fTZ5-uJe_cly5uDGM9wltaYL03GRC59G4UmEdkK97MnsLNTWNeyXA-9Z7-ZjjJazm1DhyXWIVc7qPvBUU-m8v5bYBhAst&usqp=CAE",
      precio: 18000,
      stock: 15,
    },
    {
      id: 29,
      name: "Gel de Energía para Running",
      imagen: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT7nIS4Skzdp-5y_oRxxs_HuxA6n_xW90cxXGtYTJDtGUMXuAmhXNWmeHXl5Ei14k0jp_mhGlxGutfWVDkkvaAwEhGBH6wnELK0ADvVQd7mPtDTWpxW215w9Q&usqp=CAE",
      precio: 8000,
      stock: 35,
    },
    {
      id: 30,
      name: "Proteina",
      imagen: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTqsymw-bZeQutj3DIY8NUuJHF1_5ZGQcMoH5WsXiLN96tBssAoXlRGomUJcZMctsa1KOQgajTfgsATF-uJyBZq_I6lIN8w_ij0H1apzcEgExzEjSjYx41KXg&usqp=CAE",
      precio: 10000,
      stock: 25,
    },
  ];
  